/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WishlistIndexRouteImport } from './routes/wishlist/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProfileOrdersRouteImport } from './routes/profile/orders'
import { Route as ProfileFaqRouteImport } from './routes/profile/faq'
import { Route as ProfileAddressRouteImport } from './routes/profile/address'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as OrderIdRouteImport } from './routes/order/$id'

const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistIndexRoute = WishlistIndexRouteImport.update({
  id: '/wishlist/',
  path: '/wishlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileFaqRoute = ProfileFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileAddressRoute = ProfileAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/faq': typeof ProfileFaqRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/wishlist': typeof WishlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/faq': typeof ProfileFaqRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/products': typeof ProductsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/wishlist': typeof WishlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/order/$id': typeof OrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/faq': typeof ProfileFaqRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/wishlist/': typeof WishlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/profile'
    | '/order/$id'
    | '/products/$id'
    | '/profile/address'
    | '/profile/faq'
    | '/profile/orders'
    | '/products/'
    | '/profile/'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order/$id'
    | '/products/$id'
    | '/profile/address'
    | '/profile/faq'
    | '/profile/orders'
    | '/products'
    | '/profile'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/profile'
    | '/order/$id'
    | '/products/$id'
    | '/profile/address'
    | '/profile/faq'
    | '/profile/orders'
    | '/products/'
    | '/profile/'
    | '/wishlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  OrderIdRoute: typeof OrderIdRoute
  WishlistIndexRoute: typeof WishlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/': {
      id: '/wishlist/'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/faq': {
      id: '/profile/faq'
      path: '/faq'
      fullPath: '/profile/faq'
      preLoaderRoute: typeof ProfileFaqRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/address': {
      id: '/profile/address'
      path: '/address'
      fullPath: '/profile/address'
      preLoaderRoute: typeof ProfileAddressRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileAddressRoute: typeof ProfileAddressRoute
  ProfileFaqRoute: typeof ProfileFaqRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileAddressRoute: ProfileAddressRoute,
  ProfileFaqRoute: ProfileFaqRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  OrderIdRoute: OrderIdRoute,
  WishlistIndexRoute: WishlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
